CREATE TABLE IF NOT EXISTS `users` (
  id MEDIUMINT NOT NULL AUTO_INCREMENT,
  email VARCHAR(320) NOT NULL,
  uniq_email CHAR(32) NOT NULL,
  hash VARCHAR(58) NOT NULL,
  enabled CHAR(1) DEFAULT 'N',
  PRIMARY KEY (id),
  UNIQUE (email)
);